#!name=天氣 APP 即時降雨
#!desc=為 iOS 18 & macOS 15 & watchOS 11 天氣 APP 增加即時降雨預測功能
#!icon=https://developer.apple.com/assets/elements/icons/weatherkit/weatherkit-96x96_2x.png

[Rule]
DOMAIN,weather-analytics-events.apple.com,REJECT-DROP

[Script]
[WeatherKit] Availability = type=http-response, pattern=^https?:\/\/weatherkit\.apple\.com\/api\/v1\/availability\/, requires-body=1, engine=webview, script-path=https://orsmile.github.io/surge-modules/scripts/weather-kit.js
[WeatherKit] Weather = type=http-response, pattern=^https?:\/\/weatherkit\.apple\.com\/api\/v2\/weather\/, requires-body=1, binary-body-mode=1, engine=webview, script-path=https://orsmile.github.io/surge-modules/scripts/weather-kit.js

[MITM]
hostname = %APPEND% weatherkit.apple.com